AMP_OPT_LEVEL: ''
AUG:
  AUTO_AUGMENT: rand-m9-mstd0.5-inc1
  COLOR_JITTER: 0.4
  CUTMIX: 1.0
  CUTMIX_MINMAX: null
  MIXUP: 0.8
  MIXUP_MODE: batch
  MIXUP_PROB: 1.0
  MIXUP_SWITCH_PROB: 0.5
  RECOUNT: 1
  REMODE: pixel
  REPROB: 0.25
BASE:
- ''
DATA:
  BATCH_SIZE: 396
  DATASET: imagenet
  DATA_PATH: ./
  IMG_SIZE: 64
  INTERPOLATION: bicubic
  NORMALIZATION: 0-1
  NUM_WORKERS: 8
EVAL_MODE: false
LOCAL_RANK: 0
MODEL:
  BACKBONE: efficientnet-b0
  DROP_PATH_RATE: 0.1
  DROP_RATE: 0.0
  LABEL_SMOOTHING: 0.1
  NUM_CLASSES:
  - 60
  - 30
  - 60
  PITCH_MAX: 0
  PITCH_MIN: -90
  RESUME: ''
  ROLL_MAX: 90
  ROLL_MIN: -90
  YAW_MAX: 90
  YAW_MIN: -90
OUTPUT: ''
PRINT_FREQ: 10
SAVE_FREQ: 1
SEED: 0
TAG: default
TEST:
  CROP: true
THROUGHPUT_MODE: false
TRAIN:
  ACCUMULATION_STEPS: 0
  AUTO_RESUME: true
  BASE_LR: 0.0001
  CLIP_GRAD: 5.0
  CLS_LOSS: smoothCE
  EPOCHS: 300
  FCN_LOSS: dice
  LOSS_RATIOS:
    CLS: 10
    FIN: 0.5
    REG: 1
    SEG: 0.1
  LR_SCHEDULER:
    DECAY_EPOCHS: 30
    DECAY_RATE: 0.1
    NAME: cosine
  MIN_LR: 5.0e-06
  OPTIMIZER:
    BETAS:
    - 0.9
    - 0.999
    EPS: 1.0e-08
    MOMENTUM: 0.9
    NAME: adamw
  REG_LOSS: l1
  SAVE_DIR: ./models
  START_EPOCH: 0
  USE_CHECKPOINT: false
  WARMUP_EPOCHS: 0
  WARMUP_LR: 5.0e-07
  WEIGHT_DECAY: 0.05
