MODEL: 
  BACKBONE: "efficientnet-b0"
  # https://github.com/qubvel/segmentation_models.pytorch#encoders-
  NUM_CLASSES:
  - 60
  - 30
  - 60
  RESUME: ""

TRAIN:
  BASE_LR: 0.0001
  WARMUP_EPOCHS: 0

DATA:
  BATCH_SIZE: 396
